[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "aave-v3-core/=lib/aave-v3-core/", 
    "openzeppelin-contracts/=lib/openzeppelin-contracts/"    
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config